// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/car.dart';
import 'models/maintenance_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5036840541231156310),
    name: 'Car',
    lastPropertyId: const obx_int.IdUid(4, 2809910555076086610),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6019407836367773666),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2830549668235430184),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7931010887949808685),
        name: 'year',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2809910555076086610),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8514955426232106603),
    name: 'MaintenanceRecord',
    lastPropertyId: const obx_int.IdUid(4, 7695837504483404811),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3062876870430893801),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7396299741254467690),
        name: 'carId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8094380724570152207),
        relationTarget: 'Car',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3241665608789062028),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7695837504483404811),
        name: 'detail',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8514955426232106603),
    lastIndexId: const obx_int.IdUid(1, 8094380724570152207),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Car: obx_int.EntityDefinition<Car>(
      model: _entities[0],
      toOneRelations: (Car object) => [],
      toManyRelations: (Car object) => {},
      getId: (Car object) => object.id,
      setId: (Car object, int id) {
        object.id = id;
      },
      objectToFB: (Car object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final yearOffset = fbb.writeString(object.year);
        final imagePathOffset = fbb.writeString(object.imagePath);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, yearOffset);
        fbb.addOffset(3, imagePathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final yearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Car(
          id: idParam,
          name: nameParam,
          year: yearParam,
          imagePath: imagePathParam,
        );

        return object;
      },
    ),
    MaintenanceRecord: obx_int.EntityDefinition<MaintenanceRecord>(
      model: _entities[1],
      toOneRelations: (MaintenanceRecord object) => [object.car],
      toManyRelations: (MaintenanceRecord object) => {},
      getId: (MaintenanceRecord object) => object.id,
      setId: (MaintenanceRecord object, int id) {
        object.id = id;
      },
      objectToFB: (MaintenanceRecord object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final detailOffset = fbb.writeString(object.detail);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.car.targetId);
        fbb.addOffset(2, typeOffset);
        fbb.addOffset(3, detailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final detailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = MaintenanceRecord(
          id: idParam,
          type: typeParam,
          detail: detailParam,
        );
        object.car.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.car.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Car] entity fields to define ObjectBox queries.
class Car_ {
  /// See [Car.id].
  static final id = obx.QueryIntegerProperty<Car>(_entities[0].properties[0]);

  /// See [Car.name].
  static final name = obx.QueryStringProperty<Car>(_entities[0].properties[1]);

  /// See [Car.year].
  static final year = obx.QueryStringProperty<Car>(_entities[0].properties[2]);

  /// See [Car.imagePath].
  static final imagePath = obx.QueryStringProperty<Car>(
    _entities[0].properties[3],
  );
}

/// [MaintenanceRecord] entity fields to define ObjectBox queries.
class MaintenanceRecord_ {
  /// See [MaintenanceRecord.id].
  static final id = obx.QueryIntegerProperty<MaintenanceRecord>(
    _entities[1].properties[0],
  );

  /// See [MaintenanceRecord.car].
  static final car = obx.QueryRelationToOne<MaintenanceRecord, Car>(
    _entities[1].properties[1],
  );

  /// See [MaintenanceRecord.type].
  static final type = obx.QueryStringProperty<MaintenanceRecord>(
    _entities[1].properties[2],
  );

  /// See [MaintenanceRecord.detail].
  static final detail = obx.QueryStringProperty<MaintenanceRecord>(
    _entities[1].properties[3],
  );
}
